<?php

return [
    'products' => [
        'en' => 'products',
        'es' => 'productos',
        'pt' => 'produtos',
        'it' => 'prodotti',
        'ru' => 'produkty',
    ],
    'category' => [
        'en' => 'category',
        'es' => 'categoria',
        'pt' => 'categoria',
        'it' => 'categoria',
        'ru' => 'kategoriya',
    ],
    'system' => [
        'en' => 'system',
        'es' => 'sistema',
        'pt' => 'sistema',
        'it' => 'sistema',
        'ru' => 'sistema',
    ],
    'inspire' => [
        'en' => 'inspire',
        'es' => 'inspira',
        'pt' => 'inspirar',
        'it' => 'ispirare',
        'ru' => 'okrylyayet',
    ],
    'thanks' => [
        'en' => 'thanks',
        'es' => 'gracias',
        'pt' => 'obrigada',
        'it' => 'grazie',
        'ru' => 'blagodaryu',
    ],
    'da' => [
        'en' => 'distributor-area',
        'es' => 'zona-empresarios',
        'pt' => 'zona-negocios',
        'it' => 'area-imprenditori',
        'ru' => 'oblast-predprinimateley',
    ],
    'shopping' =>[
        'en' => 'shopping',
        'es' => 'compras',
        'pt' => 'suacompra',
        'it' => 'acquisti',
        'ru' => 'pokupka',
    ],
    'checkout' => [
        'en' => 'checkout',
        'es' => 'checkoutes',
        'pt' => 'checkoutpt',
        'it' => 'checkoutit',
        'ru' => 'zavershenie-pokupki',
    ],
    'checkout_url' => [
        'en' => 'checkout',
        'es' => 'checkout',
        'pt' => 'checkout',
        'it' => 'checkout',
        'ru' => 'zavershenie-pokupki',
    ],
    'register' =>[
        'en' => 'register',
        'es' => 'registro',
        'pt' => 'cadastro',
        'it' => 'iscrizione',
        'ru' => 'registaciya',
    ],
    'confirmation' => [
        'en' => 'confirmation',
        'es' => 'confirmacion',
        'pt' => 'confirmacionpt',
        'it' => 'confirmacionit',
        'ru' => 'confirmacionru',
    ],
    'reset-password' => [
        'en' => 'reset-password',
        'es' => 'restaurar-contrasena',
        'pt' => 'redefinir-senha',
        'it' => 'reimpostare-password',
        'ru' => 'sbrosit-parol',
    ],
    'option' => [
        'en' => 'option',
        'es' => 'opcion',
        'pt' => 'optionpt',
        'it' => 'optionpt',
        'ru' => 'optionru',
    ],
    'birthdate' => [
        'en' => 'birthdate',
        'es' => 'fecha-de-nacimiento',
        'pt' => 'birthdatept',
        'it' => 'birthdateit',
        'ru' => 'birthdateru',
    ],
    'question' => [
        'en' => 'question',
        'es' => 'pregunta',
        'pt' => 'questionpt',
        'it' => 'questionit',
        'ru' => 'questionru',
    ],
    'new_password' => [
        'en' => 'new_password',
        'es' => 'nueva-contrasena',
        'pt' => 'new_passwordpt',
        'it' => 'new_passwordit',
        'ru' => 'new_passwordru',
    ],
    'login' => [
        'en' => 'login',
        'es' => 'acceso',
        'pt' => 'loginpt',
        'it' => 'loginit',
        'ru' => 'loginru',
    ],
    'code' => [
        'en' => 'code',
        'es' => 'codigo',
        'pt' => 'codept',
        'it' => 'codeit',
        'ru' => 'coderu',
    ],
    'client-register' =>[
        'en' => 'client-register',
        'es' => 'registro-cliente',
        'pt' => 'cadastro-cliente',
        'it' => 'iscrizione-cliente',
        'ru' => 'registraciya-clienta',
    ],
    'activation' =>[
        'en' => 'activation',
        'es' => 'activacion',
        'pt' => 'activationpt',
        'it' => 'activationit',
        'ru' => 'activationru',
    ],
    'registercustomer' => [
        'en' => 'registercustomer',
        'es' => 'registercustomeres',
        'pt' => 'registercustomerpt',
        'it' => 'registercustomerit',
        'ru' => 'registercustomerru',

    ]
];
